title: Sangmin Sandy Lee 
description: Data Analyst | Computational Social Science | UC Berkeley
theme: jekyll-theme-minimal
github:
  is_project_page: false
  repository_url: https://github.com/sandy-lee29